In [1]:
import torch

In [91]:
bruh = torch.randint(1, 5, (3,3), generator=torch.Generator()) 
print(bruh)
print(bruh.sum(1))
print(bruh.sum(1).shape)
bruh = bruh * bruh.sum(1)

bruh

tensor([[3, 1, 2],
        [1, 2, 4],
        [3, 3, 4]])
tensor([ 6,  7, 10])
torch.Size([3])


tensor([[18,  7, 20],
        [ 6, 14, 40],
        [18, 21, 40]])

In [76]:
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5], [7]])
print(B.shape)
C = A * B  # Matrix multiplication
print(C)


torch.Size([2, 1])
tensor([[ 5, 10],
        [21, 28]])
